# Generated by Django 5.0 on 2023-12-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(auto_created=True, default=1000)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_national_id', models.IntegerField(max_length=25)),
                ('birth_date', models.DateField(max_length=8)),
                ('employee_phone_1', models.IntegerField(max_length=25)),
                ('employee_phone_2', models.IntegerField(max_length=25)),
                ('governorate', models.CharField(max_length=25)),
                ('employee_email', models.CharField(max_length=50)),
            ],
        ),
    ]
