# Generated by Django 5.0 on 2023-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_employee_phone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='employee/'),
            preserve_default=False,
        ),
    ]
