# Generated by Django 5.0 on 2023-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_phone_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/employee/images/'),
        ),
    ]
