# Generated by Django 5.0 on 2024-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employee_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_national_id',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
