# Generated by Django 5.0 on 2024-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_employee_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
