# Generated by Django 5.0 on 2024-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_employee_employee_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_national_id',
            field=models.BigIntegerField(),
        ),
    ]
