# Generated by Django 5.0 on 2023-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.IntegerField(auto_created=True, default=7044000, max_length=8)),
                ('device_type', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Printer', 'Printer')], max_length=15)),
                ('model_name', models.CharField(max_length=15)),
                ('motherboard', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('hdd', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=50)),
                ('sites', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('other', models.TextField(max_length=255)),
            ],
        ),
    ]
