# Generated by Django 5.0 on 2023-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_date_alter_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
