# Generated by Django 5.0 on 2024-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_code',
            field=models.IntegerField(auto_created=True, default=7040000, unique=True),
        ),
    ]
