# Generated by Django 5.0 on 2024-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_alter_device_cpu_alter_device_hdd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
