# Generated by Django 5.0 on 2024-06-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_alter_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
