# Generated by Django 5.0 on 2024-06-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_ticket_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
