# Generated by Django 5.0 on 2024-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
